# Get editor completions base3 on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# Customizing the prompt (and placing desired modules at desired position and sequence):
# â•­â•´ # \u256D\u2574
# â•°â•´ # \u2570\u2574
format = """
[â•­](fg:base0)[î‚¶](fg:base0)$username[î‚°](fg:base0 bg:base1)$hostname[î‚°](fg:base1 bg:base2)$directory\
[î‚°](fg:base2 bg:base3)$git_branch[î‚°](fg:base3 bg:base4)$git_status[î‚°](fg:base4)\
$fill\
[î‚²](fg:base4)$sudo\
[î‚²](fg:base3 bg:base4)\
$cmd_duration\
[î‚²](fg:base2 bg:base3)\
$jobs\
[î‚²](fg:base1 bg:base2)\
$shell\
[î‚²](fg:base0 bg:base1)\
$time\
[î‚´](fg:base0)\
$line_break\
[â•°â”€](fg:base0)$status\
$character"""

# Inserts a blank line between shell prompts
add_newline = true

# color palette
palette = "gandert"

[character]
disabled = false
success_symbol = "[â¯](green) "
error_symbol = "[ğŸ”¥](bold red) "
#error_symbol = "[ğŸ”¥ğŸ§¨Ã—ğŸ“›ğ•ğ”µâ¦»âœ—âŠ—âŒ](bold red) "
format = "$symbol"

[cmd_duration]
min_time = 2500
show_notifications = false
format = "[ ï”  $duration ]($style)"
style = "fg:text0 bg:base3"

[directory]
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "â€¦/"
home_symbol = "~"
read_only = "ó°ˆˆ "
#read_only_style = "bg:base1"
format = "[ $path $read_only]($style)"
style = "fg:text0 bg:base2"

[fill]
#symbol = " "
symbol = "â”€"
style = "fg:base0"

[git_branch]
symbol = "îœ¥ "
truncation_length = 6
truncation_symbol = ""
format = "[ $symbol$branch(:$remote_branch) ]($style)"
style = "fg:text0 bg:base3"

[git_status]
#up_to_date = "âœ“"
format = "[$all_status$ahead_behind]($style)"
style = "fg:text0 bg:base4"

[hostname]
disabled = false
ssh_only = true
style = "fg:text0 bg:base1"
format = "[$ssh_symbol @ $hostname]($style)"

[jobs]
symbol = "ó°£–"
#number_threshold = 4
#symbol_threshold = 0
#symbol_threshold = 1
format = "[$symbol $number ]($style) "
style = "fg:text0 bg:base2"

[line_break]
disabled = false

[shell]
disabled = false
bash_indicator = "bsh"
zsh_indicator = "zsh"
unknown_indicator = "mystery shell"
format = "[ $indicator ]($style)"
style = "fg:text0 bg:base1"

[sudo]
disabled = false
symbol = "ó°Œ‹"
format = "[ $symbol ]($style)"
style = "fg:text0 bg:base4"

[time]
disabled = false
time_format = "%T"
format = "[ $time]($style)"
style = "fg:text0 bg:base0"
time_range = "08:00:00-16:30:00"

[username]
disabled = false
show_always = true
format = "[$user]($style)"
style_user = "fg:text0 bg:base0"
style_root = "fg:red bg:base0"

[palettes.gandert]
base0 = "#45475a"
base1 = "#57596a"
base2 = "#6a6b7a"
base3 = "#7c7e8b"
base4 = "#8f909c"
#base5 = "#a2a3ac" # not used
#base6 = "#b4b5bd" # not used
#base7 = "#c7c7cd" # not used
#base8 = "#d9dade" # not used
#base9 = "#ececee" # not used
#basek = "#ffffff" # not used = white
text0 = "#ececee"
